---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: entrypoint
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/prod/apps
    repoURL: https://github.com/pumphouse-p/aap-on-ocp.git
    targetRevision: main
  syncPolicy:
    automated: {}