---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/targetNamespaces
        value: []
    target:
      kind: OperatorGroup
      name: ansible-automation-platform-operator
  - target:
      kind: Subscription
      name: ansible-automation-platform
    path: patch-channel.yaml