---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: example
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  image_pull_policy: IfNotPresent
  controller:
    disabled: false
    replicas: 1
  eda:
    disabled: false
    replicas: 1
  hub:
    disabled: false
    storage_type: file
    file_storage_storage_class: gp3-csi
    replicas: 1
  lightspeed:
    disabled: true
