---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ansible-automation-platform-operator
  namespace: openshift-gitops
spec:
  project: default
  source:
    path: manifests/ansible-automation-platform/operator
    repoURL: git@github.com/pumphouse-p/aap-on-ocp
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}